# Generated by Django 5.1.1 on 2024-09-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(default='', max_length=150)),
                ('products_price', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('products_description', models.CharField(default='', max_length=150)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
