# Generated by Django 5.1.1 on 2024-09-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sale_total', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductSale_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('ProductSale_quantity', models.IntegerField()),
                ('ProductSale_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.products')),
                ('ProductSale_sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
