# Generated by Django 5.1.1 on 2024-09-28 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_sale_productsale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='products_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='products_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='products_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productsale',
            old_name='ProductSale_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productsale',
            old_name='ProductSale_product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='productsale',
            old_name='ProductSale_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='productsale',
            old_name='ProductSale_sale_id',
            new_name='sale_id',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='Sale_total',
            new_name='total',
        ),
    ]
